import * as lucide from 'lucide-react';
export const Icon = {
  home: lucide.Home,
  user: lucide.User,
  paw: lucide.PawPrint,
  calendar: lucide.CalendarDays,
  back: lucide.ArrowBigLeftDashIcon,
  file: lucide.FileText,
  receiveCoins: lucide.HandCoins,
  handShake: lucide.Handshake,
  pigBank: lucide.PiggyBank,
  box: lucide.Box,
  fileBox: lucide.FileBox,
  package: lucide.Package,
  openPackage: lucide.PackageOpen,
  sheet: lucide.Sheet,
  arrowDownUp: lucide.ArrowDownUp,
  arrowDownAZ: lucide.ArrowDown,
  arrowUpAZ: lucide.ArrowUp,
  eyeClose: lucide.EyeOff,
  x: lucide.X,
  backButton: lucide.ChevronLeft,
  moreHorizontal: lucide.MoreHorizontal,
  squarePen: lucide.SquarePen,
  shower: lucide.ShowerHead,
  pencilRuler: lucide.PencilRuler,
  contact: lucide.ContactRound,
  truck: lucide.Truck,
  report: lucide.FileLineChart,
  config: lucide.Settings,
  dog: lucide.Dog,
  cat: lucide.Cat,
  squareArrow: lucide.SquareArrowOutUpRight,
  triangleWarn: lucide.TriangleAlert,
  sun: lucide.Sun,
  moon: lucide.Moon,
  logOut: lucide.LogOut,
  plus: lucide.Plus,
  leftChevron: lucide.ChevronLeft,
  rightChevron: lucide.ChevronRight,
  calculate: lucide.Calculator,
  dashboard: lucide.LayoutDashboard,
  clock: lucide.Clock,
  service: lucide.HandPlatter,
  notedPad: lucide.NotepadText,
  gridLayout: lucide.LayoutGrid,
  stretchHorizontal: lucide.StretchHorizontal,
};

export type LucideIcon = lucide.LucideIcon;
